theme: jekyll-theme-time-machine
title: Perfil de Samuel Rocha
description: Perfil acadêmico profissional do Prof. Dr. Samuel Rocha de Oliveira
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
